/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2022-04-14 07:21:51
 */
import { Attributes, Commands, CommandsNoResult } from './commands';
import { CsvExportFormatOptions, CsvExportOptions, CsvFormatOptions, CsvImportOptions } from './import/types';
import { QueryResult } from './query-result';
import { SQLQueriesResponse, SQLResponse } from './types';

export type Cancelable = () => void;

export type CetCancelFunction = (cancel?: Cancelable) => void;

/** Browser-safe driver contract without Node.js local-file operations. */
export interface IExasolClient extends AsyncDisposable {
  /**
   * Connect to database
   *
   * @throws {Error}
   * @returns {Promise.<void>}
   */
  connect(): Promise<void>;
  /**
   * Cancel the last active job
   */
  cancel(): Promise<void>;
  /**
   *  Close current connection
   */
  close(): Promise<void>;

  /**
   * Query single SQL statement
   *
   * @param {string} sqlStatement
   * @param {Partial<Attributes>} attributes
   * @throws {Error}
   * @returns {Promise.<SQLResponse<SQLQueriesResponse>>}
   */
  query(sqlStatement: string, attributes?: Partial<Attributes>, getCancel?: CetCancelFunction): Promise<QueryResult>;
  query(
    sqlStatement: string,
    attributes?: Partial<Attributes>,
    getCancel?: CetCancelFunction,
    responseType?: 'default'
  ): Promise<QueryResult>;

  /**
   * Query single SQL statement and get raw result
   *
   * @param {string} sqlStatement
   * @param {Partial<Attributes>} attributes
   * @throws {Error}
   * @returns {Promise.<SQLResponse<SQLQueriesResponse>>}
   */
  query(
    sqlStatement: string,
    attributes?: Partial<Attributes>,
    getCancel?: CetCancelFunction,
    responseType?: 'raw'
  ): Promise<SQLResponse<SQLQueriesResponse>>;

  /**
   * Execute single SQL statement
   *
   * @param {string} sqlStatement
   * @param {Partial<Attributes>} attributes
   * @throws {Error}
   * @returns {Promise.<number>}
   */
  execute(sqlStatement: string, attributes?: Partial<Attributes>, getCancel?: CetCancelFunction): Promise<number>;
  execute(sqlStatement: string, attributes?: Partial<Attributes>, getCancel?: CetCancelFunction, responseType?: 'default'): Promise<number>;

  /**
   * Execute single SQL statement and get raw result back
   *
   * @param {string} sqlStatement
   * @param {Partial<Attributes>} attributes
   * @throws {Error}
   * @returns {Promise.<SQLResponse<SQLQueriesResponse>>}
   */
  execute(
    sqlStatement: string,
    attributes?: Partial<Attributes>,
    getCancel?: CetCancelFunction,
    responseType?: 'raw'
  ): Promise<SQLResponse<SQLQueriesResponse>>;

  /**
   * Executes multiple SQL statements sequentially as a batch.
   *
   * @param {string[]} sqlStatements - Array of sql statements
   * @param {Partial<Attributes>} attributes
   * @throws {Error}
   * @returns {Promise.<SQLResponse<SQLQueriesResponse>>}
   */
  executeBatch(
    sqlStatements: string[],
    attributes?: Partial<Attributes>,
    getCancel?: CetCancelFunction
  ): Promise<SQLResponse<SQLQueriesResponse>>;
  /**
   * Prepare statement
   *
   * @param  {string} sqlStatement
   * @throws {Error}
   * @returns {Promise.<IStatement>}
   */
  prepare(sqlStatement: string): Promise<IStatement>;
  /**
   * Send commands which have no results
   * @param {CommandsNoResult} cmd
   */
  sendCommandWithNoResult(cmd: CommandsNoResult): Promise<void>;
  /**
   * Send commands and wait for result, while a command is executed all other commands will be rejected till the current command finished.
   * @param  {Commands} cmd
   * @throws {Error}
   * @template T
   * @returns {Promise.<SQLResponse<T>>}
   */
  sendCommand<T>(cmd: Commands): Promise<SQLResponse<T>>;
}

/** Node.js driver contract including local CSV import and export. */
export interface IExasolDriver extends IExasolClient {

  /**
   * Import data from a local CSV file into an Exasol table.
   *
   * Node.js only.
   *
   * @param tableName Target table name (optionally schema-qualified)
   * @param filePath Path to the local CSV file
   * @param csvOptions Optional CSV format options
   * @param options Optional import control options
   * @returns Number of rows imported
   */
  importFromCsvFile(tableName: string, filePath: string, csvOptions?: CsvFormatOptions, options?: CsvImportOptions): Promise<number>;

  /**
   * Export an Exasol table or parenthesized query result to a new local CSV file.
   *
   * Node.js only.
   *
   * @param source Source table name (optionally schema-qualified) or parenthesized query
   * @param filePath Path to the new local CSV file
   * @param csvOptions Optional CSV format options
   * @param options Optional export control options
   * @returns Number of rows exported
   */
  exportToCsvFile(source: string, filePath: string, csvOptions?: CsvExportFormatOptions, options?: CsvExportOptions): Promise<number>;
}

export interface IStatement extends AsyncDisposable {
  /**
   * Close statement
   */
  close(): Promise<void>;
  /**
   *  Execute prepared statement with given args
   *
   * @param {...any} args
   * @throws {Error}
   * @returns {Promise.<SQLResponse<SQLQueriesResponse>>}
   */
  execute(...args: Array<unknown>): Promise<SQLResponse<SQLQueriesResponse>>;
}
