name: Main
on:
  push:
    branches:
      - main
jobs:
  distributed-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        target: ['lint:ci', 'test:all', 'build']
    env:
      DEFAULT_TARGET: 'test:all'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version: '26'
          cache: 'npm'
      - name: Free Disk Space
        if: ${{ matrix.target == 'test:all' }}
        run: |
          df -h
          echo "Cleaning up disk space by removing unnecessary files..."
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          df -h
      - run: npm ci --ignore-scripts
      - run: npm run ${{ matrix.target }}
      - name: Run audit
        if: ${{ matrix.target == env.DEFAULT_TARGET }}
        run: npm run audit
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        if: ${{ matrix.target == env.DEFAULT_TARGET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
