name: Release
on:
  push:
    branches:
      - main
jobs:
  distributed-tasks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: ['lint:ci', 'test:dom', 'test:node', 'itest:dom', 'itest:node', 'build']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ matrix.target }}
