name: Pull Request
env:
  NPM_TOKEN: 'thisisaworkaroundfornode14'
on:
  pull_request:
jobs:
  distributed-tasks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ['lint:ci', 'test:dom', 'test:node', 'itest:dom', 'build']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: npm ci
      - run: npm run ${{ matrix.target }}
  integration-test-node:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['16', '18', '20']
    name: Node ${{ matrix.node }} integration test
    steps:
      - uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run itest:dom
