name: Release
on:
  release:
    types: [released]
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
        with:
          node-version: '26'
          package-manager-cache: false
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --ignore-scripts
      - run: npm run lint:ci
      - run: npm run typecheck
      - run: npm run trace
      - run: npm run test:all
      - run: npm run audit
      - run: npm run build
      - run: npm pack
      - name: Publish package on NPM 📦
        run: npm publish --access public
